### ISSUE TITLE
gitattributes affecting git repos

### ISSUE THREAD

**Issue by necolas** [mathiasbynens/dotfiles#149]
We've spoken about this before - the automatic line-ending substitution triggering changes in git submodules etc. But I've also come across an issue where Homebrew couldn't pull from the remote (`brew update`) because the gitattributes setting caused the Homebrew repo to enter into a dirty state.

One option would be to reassess the contents of gitattributes. The other would be to see if adding a gitattributes file to Homebrew's repo would prevent this potential problem. Maybe they should be normalizing line endings anyway, or at least protecting their code from a user's global setting.

What do you think?

**Comment by rgant** [comment]
As of git 2.10 this functions as expected https://github.com/git/git/blob/master/Documentation/RelNotes/2.10.0.txt#L248
