### ISSUE TITLE
.bashrc vs .bash_profile

### ISSUE THREAD

**Issue by wamatt** [mathiasbynens/dotfiles#165]
I'm seeing conflicting advice on this.

http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

States the bash manual and best practice is to have .bash_profile link to .bashrc, not the other way around.

Thoughts?

**Comment by Andersos** [comment]
@wamatt can this be closed?

**Comment by wamatt** [comment]
@Andersos sure
