### ISSUE TITLE
OSX 10.8.2: Setting default Terminal theme doesn't work

### ISSUE THREAD

**Issue by kevinSuttle** [mathiasbynens/dotfiles#185]
At least for me, when I run 

```
open "$HOME/Code/solarized/osx-terminal.app-colors-solarized/Solarized\ Dark\ ansi.terminal"
sleep 1 # Wait a bit to make sure the theme is loaded
defaults write com.apple.terminal "Default Window Settings" -string "Solarized Dark ansi"
defaults write com.apple.terminal "Startup Window Settings" -string "Solarized Dark ansi"
```

It never takes effect. Any ideas?

**Comment by PaulRBerg** [comment]
In my case, this happened when I was using a custom [window group][window-groups]. Going into Preferences and selecting `Solarized Dark` for `New window with profile...` fixed the issue for me.

[window-groups]: https://superuser.com/questions/11736/osx-window-groups
