### ISSUE TITLE
How to remove these dotfiles and revert the system

### ISSUE THREAD

**Issue by tabibzadeh** [mathiasbynens/dotfiles#190]
I wonder why there isn't even one discussion on how to remove these dotfiles completely. 

I just want my whole system and setup to get back where it was! 
Can you give me a hint? 

Thanks.

**Comment by saeed3e** [comment]
@Tatsh @mathiasbynens this command is not working on my mac(high sierra, version:10.13.6)
`find /Users/yourNameBak -maxdepth 1 ! -iname '.*' -exec cp -vfR {} /Users/yourName \;`

 getting error `"not a directory"`
