### ISSUE TITLE
Uninstall script?

### ISSUE THREAD

**Issue by ryanordille** [mathiasbynens/dotfiles#28]
Is there a script to uninstall/revert back to defaults? If not, this would probably be a quick improvement.

**Comment by peduarte** [comment]
I don't understand why you wouldn't want to add an uninstall script.

**Comment by cemo** [comment]
Maybe because of maintaining it?

**Comment by peduarte** [comment]
But isn't this what open source is about?
Sorry maybe I am mistaken, but a lot of people dont know their way around bas files, etc.
So considering that there is an installation script, it would only be fair to have an uninstall one.

Just an idea! I would be happy to contribute but I dont know how to do it :(

**Comment by AlecRust** [comment]
Another reason against I would argue is that this isn't really software that is installed/uninstalled. It's simply a set of configuration commands and files that Mathias uses to set up new machines. Use all of it, none of it or portions of it but don't be surprised the contributors to this project aren't interested in the maintenance overhead of a script which undoes all of these commands.

As stated, if you disagree fork this repo and add the functionality (read to learn how). If you think the functionality should be merged from your fork in to this main repo, open a PR. _That's_ what open source is about :)

**Comment by thibmaek** [comment]
> That's what open source is about :)
+1

**Comment by peduarte** [comment]
Yeah you are right, I guess that after doing some reading about exactly what is happening it makes sense. 
It's just that the installation is so simple that makes it seem like there are things being installed!

I like all the commands I was just wanting to uninstall because I switched to zsh. 

Thanks for the comments!

**Comment by stevebarakat** [comment]
I installed your dotfiles and now I'm stuck with your ugly wallpaper on my desktop. There's no way to change it. I've tried a million different ways.

**Comment by mathiasbynens** [comment]
@stevebarakat My dotfiles don’t set a wallpaper unless you uncommented that line…
