### ISSUE TITLE
Brew upgrade error

### ISSUE THREAD

**Issue by rizkysyazuli** [mathiasbynens/dotfiles#374]
I'm getting this error when running `brew bundle Brewfile`. This happens while Brew is updating Vim.

    ==> Upgrading vim
    ==> Downloading http://ftp.debian.org/debian/pool/main/v/vim/vim_7.4.273.orig.ta
    ######################################################################## 100.0%
    ==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.273/share
    ==> make
    ==> make install prefix=/usr/local/Cellar/vim/7.4.273 STRIP=true
    🍺  /usr/local/Cellar/vim/7.4.273: 1572 files, 25M, built in 99 seconds

    Error: You must `brew link nss' before xulrunner can be installed
    Error: Command failed: L8:brew upgrade

I tried to do what the error message says and run the `brew link nss`. but this is what i get:

    Linking /usr/local/Cellar/nss/3.16... 
    Error: Could not symlink lib/libplds4.dylib
    Target /usr/local/lib/libplds4.dylib
    is a symlink belonging to nspr. You can unlink it:
      brew unlink nspr

What is this xulrunner and nss thing anyway?

**Comment by Andersos** [comment]
I agree with @nvartolomei this belongs in the [Homebrew]( https://github.com/Homebrew/homebrew) issue tracker. @rizkysyazuli can this be closed?

`brew doctor` might help you get along though.

**Comment by rizkysyazuli** [comment]
yep, sure.
