### ISSUE TITLE
Issue with RVM?

### ISSUE THREAD

**Issue by iamrahulroy** [mathiasbynens/dotfiles#401]
Hi! Does installing this script have any known effect on existing RVM installation? I had RVM installed on OSX 10.9 earlier, but after installing this script I lost access to RVM.

Is there a way to uninstall this script or is there any uninstall script available? Sorry for Noobish questions.

**Comment by rhAlves42** [comment]
(English as second language, sorry about the mistakes)
i'm using ubuntu and for reset my default terminal i copy/paste the default .bashrc

this r the steps that i followed:

`rm -i ~/.profile ~/.bash*`
and replace the content 
https://gist.github.com/marioBonales/1637696

i hope that help
