### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by fulldecent** [mathiasbynens/dotfiles#429]
Fresh 10.10 install, ran commands per REDME.md, got this:

![screen shot 2014-10-07 at 21 12 53](https://cloud.githubusercontent.com/assets/382183/4552641/45e5e9ec-4e88-11e4-933c-cef7b927023d.png)

**Comment by ryanseddon** [comment]
I just tried to run this on 10.11.2 and got the `bootstrap.sh:13: = not found`?

**Comment by ryanseddon** [comment]
Hmm `sh -x bootstrap.sh` worked
