### ISSUE TITLE
Undo sleep deprivation

### ISSUE THREAD

**Issue by fulldecent** [mathiasbynens/dotfiles#433]
How do I undo the never-sleep mode? This results in my battery draining fully everytime that it is not plugged in. Effectively it turned my laptop into a desktop

**Comment by kapad** [comment]
What does the sleep setting do exactly? If I hold the power button or close the lid, will my computer still go to sleep? 
@mathiasbynens

**Comment by guerrero** [comment]
@kapad you can check how `pmset` works [here](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/pmset.1.html), examples are really helpful.
