### ISSUE TITLE
NSTextShowsControlCharacters setting causes Mail to freeze

### ISSUE THREAD

**Issue by nickcooley** [mathiasbynens/dotfiles#465]
I'm not sure if this is a larger issue (and I suspect it's not given that no one has reported it before), but setting `
defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true`   seems to cause my Apple Mail app  (MBP 2014 15" Retina OSX 10.10.1) to irreparably freeze when scrolling up and down the message list.  This was a really weird issue that I thought had to do with the scroll settings, but when setting `defaults delete NSGlobalDomain NSTextShowsControlCharacters`, the issue was resolved.  

Again,  not sure how widespread this issue is, but I thought I would pass it along.   Happy to pass along any of the forensics, but since this isn't really software, but rather configuration, I thought it might help someone one day.

**Comment by hackruu** [comment]
Oh well, defaults delete NSGlobalDomain NSTextShowsControlCharacters fixes same freeze on Mail.app for me. Thanks alot, i was mad because of this freezes :+1:

**Comment by p3k** [comment]
+1

**Comment by olekristensen** [comment]
+1

**Comment by adriantofan** [comment]
+1 
btw also crashes HTTPScoop for the same reason

**Comment by ds82** [comment]
I can confirm the mail.app crashes

**Comment by natecavanaugh** [comment]
+1 Thank you @nickcooley and @twayz. I was having a very similar issue with the QLStephen plugin that has been driving me nuts for the past 6 months, crashing the Finder with the `_NSGlyphTreeInsertGlyphs glyph index issue 2` error.
I don't know why it seems to happen for some and not others, but I will say I'm glad I know now which setting triggering it for me, and hopefully any others running into it will be able to find it via Google.

**Comment by MyopicPaideia** [comment]
+1 to this, been having heavy crashing issues with Mail.app since 10.10.1 on a 2011 11" MBA.

Having a problem copying and pasting this into Terminal, it is giving me the following error, can anyone help this noob implement the setting so I can see if it fixes my issue?

2015-04-21 16:10:07.880 defaults[2133:276020] 
Domain (kCFPreferencesAnyApplication) not found.
Defaults have not been changed.

**Comment by nickcooley** [comment]
@MyopicPaideia  -- 

That's what you get when the offending key is no longer present (I see the same thing when I try to delete that key).  You should be all set?  What happens when you check for other keys in the .osx file?

For example: ```defaults read com.apple.finder EmptyTrashSecurely``` should output as: ```1```  if you're using these dotfiles?  You could then try to run it again and delete to be sure?

**Comment by MyopicPaideia** [comment]
@nickcooley --

Thanks for your reply. That's obviously not the source of my woes with Mail.app. Everything else with 10.10.1+ (now on 10.10.3) has been excellent, no issues at all. Mail.app constantly freezes up and Force Quit is required - at least 4-5 times daily, on a good day - sometimes double that. In addition, I can reproduce a crash/freeze consistently when trying to open Mail.app preferences. I get the following in the crash log - the second part just repeats itself over and over again. I have been everywhere, on the phone with Apple Support, the suppport communites on Apple's website [here] (https://discussions.apple.com/thread/6801271), got nothing, praying for an answer here!:

Heaviest stack for the main thread of the target process:
  18  ??? [0x1153855c9]
  18  ??? [0x111dc5354]
  18  ??? [0x111e48bf3]
  18  ??? [0x111e52f68]
  18  ??? [0x111e53d0d]
  18  ??? [0x111f1cde0]
  18  ??? [0x11a96c0fe]
  18  ??? [0x11a96c481]
  18  ??? [0x11a96ba09]
  18  ??? [0x11a96bb30]
  18  ??? [0x11a96bb8d]
  18  ??? [0x11a92df45]
  18  ??? [0x11a8f3cb6]
  18  ??? [0x11a8ddfae]
  18  ??? [0x11a8deb6c]
  18  ??? [0x111ffee6b]
  18  ??? [0x1120dd9c2]
  18  ??? [0x1120ddb76]
  18  ??? [0x1120ddc10]
  18  ??? [0x1156bdcd7]
  18  ??? [0x112016a7c]
  18  ??? [0x112016d4e]
  18  ??? [0x112016fb1]
  18  ??? [0x1156bdcd7]
  18  ??? [0x1100a3e30]
  18  ??? [0x11243b9a5]
  18  ??? [0x111eefab2]
  18  ??? [0x111ef84eb]
  18  ??? [0x111ef8897]
  18  ??? [0x111ef95b2]
  18  ??? [0x111e56b19]
  18  ??? [0x111e572be]
  18  ??? [0x111e9f79b]
  18  ??? [0x111ea3403]
  18  ??? [0x111ea3ca6]
  18  ??? [0x111ea620e]
  18  ??? [0x111ea620e]
  18  ??? [0x111ea620e]
  18  ??? [0x111ea620e]
  18  ??? [0x111ea5e0a]
  18  ??? [0x111efc0ca]
  18  ??? [0x111ea6898]
  18  ??? [0x111eacd68]
  18  ??? [0x1147af3ae]
  18  ??? [0x1147afaf1]
  18  ??? [0x1147b5ca2]
  18  ??? [0x1147b5ca2]
  18  ??? [0x1147b5ca2]
  18  ??? [0x1147b5ca2]
  18  ??? [0x1147b5ca2]
  18  ??? [0x1147b5ca2]
  18  ??? [0x1147b5d21]
  18  ??? [0x1147b5df5]
  18  ??? [0x1147b66c5]
  18  ??? [0x111e638bb]
  18  ??? [0x111e6392a]
  18  ??? [0x111e63f80]
  18  ??? [0x111e5fed6]
  18  ??? [0x111e64278]
  18  ??? [0x111e64646]
  18  ??? [0x111ec144a]
  18  ??? [0x111ec1606]
  18  ??? [0x111eb9b50]
  18  ??? [0x111ec1b45]
  18  ??? [0x111eb92a5]
  18  ??? [0x111eb993b]
  18  ??? [0x111eb9d7d]
  18  ??? [0x111eb9f3d]
  18  ??? [0x111fb3bc8]
  18  ??? [0x111fb5c2c]
  18  ??? [0x111eb7e3e]
  18  ??? [0x111eb8ae7]
  18  ??? [0x111e5fed6]
  18  ??? [0x1123a9676]
  18  ??? [0x111eb92a5]
  18  ??? [0x111eb993b]
  18  ??? [0x111eb9d7d]
  18  ??? [0x111eb9f3d]
  18  ??? [0x111eba097]
  18  ??? [0x111e62ba3]
  18  ??? [0x111dd108b]
  18  ??? [0x111e62bea]
  18  ??? [0x11adafd6e]
  18  ??? [0x11ad73391]
  18  ??? [0x11ad9708f]
  18  ??? [0x11adbe139]
  18  ??? [0x11bc0e602]
  18  ??? [0x11bc0ce20]
  18  ??? [0x11bc1fb60]
  18  ??? [0x11555151a]
 *18  semaphore_wait_continue + 0 (kernel + 1357760) [0xffffff800034b7c0]


Process:         Mail [3705]
Path:            /Applications/Mail.app/Contents/MacOS/Mail
Architecture:    x86_64
Parent:          launchd [1]
UID:             502
Sudden Term:     Dirty
Task size:       46693 pages
CPU Time:        0.006s
Note:            Unresponsive for 22 seconds before sampling
Dispatch Thread Hard Limit Reached:  512  (too many dispatch threads blocked in synchronous operations)

  Thread 0xbc0c       DispatchQueue 1     18 samples (1-18)   priority 44
  <frontmost, thread QoS user interactive, boosted, received importance donation from WindowServer [163], IO policy important>
  18  ??? [0x1153855c9] 1-18
    18  ??? [0x111dc5354] 1-18
      18  ??? [0x111e48bf3] 1-18
        18  ??? [0x111e52f68] 1-18
          18  ??? [0x111e53d0d] 1-18
            18  ??? [0x111f1cde0] 1-18
              18  ??? [0x11a96c0fe] 1-18
                18  ??? [0x11a96c481] 1-18
                  18  ??? [0x11a96ba09] 1-18
                    18  ??? [0x11a96bb30] 1-

**Comment by AnilRh** [comment]
+1 seems to have fixed my issue.

**Comment by aaronharding** [comment]
This also crashes my Finder with the `Finder[4963]: !!! _NSGlyphTreeInsertGlyphs glyph index issue 2` error.

**Comment by aaronharding** [comment]
Running `defaults delete NSGlobalDomain NSTextShowsControlCharacters` fixes that.

**Comment by thijsc** [comment]
I had the exact same issue, setting to defaults fixed it for me.

**Comment by eyuelt** [comment]
+1

**Comment by Sciscitator** [comment]
This didn't only affect Mail, it was crashing the Notification Center as soon as it started and continuously caused CrashReport process to have 30-40% cpu usage.

Luckily "defaults delete NSGlobalDomain NSTextShowsControlCharacters" fixed this annoying issue. Thanks!

**Comment by mklaber** [comment]
:+1:

**Comment by johntrandall** [comment]
+1 Thank you.

**Comment by davidgorges** [comment]
This also crashed the finder preview thumb generation (e.g. for InDesign documents) and caused Mail to hang on startup. Resetting via `defaults delete NSGlobalDomain NSTextShowsControlCharacters` helped. Problem solved!
