### ISSUE TITLE
GREP_OPTIONS is deprecated

### ISSUE THREAD

**Issue by ribmo** [mathiasbynens/dotfiles#467]
I get the following error with grep (GNU grep) 2.21:

`grep: warning: GREP_OPTIONS is deprecated; please use an alias or script`

This appears when I open my shell and anytime I attempt to run `grep` (preventing `grep` from actually running). 

This is due to this line in .exports: [`export GREP_OPTIONS="--color=auto";`](https://github.com/mathiasbynens/dotfiles/blob/f0997a53bf10afdf3f09af8a9728c173c5dabfe1/.exports#L22)

According to [grep's manual](http://www.gnu.org/software/grep/manual/html_node/Environment-Variables.html):

> `GREP_OPTIONS`
> This variable specifies default options to be placed in front of any explicit options. As this causes problems when writing portable scripts, this feature will be removed in a future release of grep, and grep warns if it is used. Please use an alias or script instead.

**Comment by webpro** [comment]
The fix can be simple: https://github.com/webpro/dotfiles/commit/79f9fa724b3986962002d18107da6ff8ef26ef4d

**Comment by BillSantos** [comment]
`$ env | grep -i grep`
`grep: warning: GREP_OPTIONS is deprecated; please use an alias or script`
`GREP_OPTIONS=--color=auto`

`$ grep --version`
`grep (GNU grep) 2.21`

I fixed this in my fork of mathiasbynens/dotfiles.

I used **webpro's** solution, found at [webpro/dotfiles@79f9fa7.][a]

[a]: https://github.com/webpro/dotfiles/commit/79f9fa724b3986962002d18107da6ff8ef26ef4d "webpro/dotfiles"

I find Mathias' dotfiles extremely useful on multiple platforms, including Linux and OS X. I got this error consistently on platforms that use GNU grep (Linux nattive and OS X modified for use of GNU command line tools via Homebrew, MacPorts or Fink).

The native OS X grep is 2.5.1-FreeBSD, and does not report this error.

Please consider moving color support for grep from *.exports* to *.aliases* to avoid this problem for those of us using your repo with GNU grep:

`alias grep="grep $GREP_OPTIONS"`

Thanks for all your great work, Mathias!

**Comment by mathiasbynens** [comment]
@BillSantos Would you mind submitting a pull request for that?

**Comment by BillSantos** [comment]
@mathiasbynens 
Mathias, see my pull request [#590.](https://github.com/mathiasbynens/dotfiles/pull/590 "Move GREP_OPTIONS")

Thanks for your consideration.

**Comment by rfabbri** [comment]
The alias solution won't color output if input is from pipe. And of course I use grep in pipes most of the time..

**Comment by mathiasbynens** [comment]
@rfabbri Me too. Do you know of a solution that doesn’t have this problem?

**Comment by rfabbri** [comment]
For now I'm using a script layer, described in my answer to this question:
http://askubuntu.com/questions/2186/replace-grep-command-with-grep-n-colour/778329#778329

**Comment by heitorPB** [comment]
`find /usr/share -name '*.txt' |xargs grep --color testing` works for me. But it is quite painful to have to write what I already have in my alias..

**Comment by Justsoos** [comment]
> The alias solution won't color output if input is from xargs in a pipe. And of course I use grep in pipes with xargs most of the time.. eg: `find /usr/share -name '*.txt' |xargs grep testing`

now I run more ack than grep, ack has colored result as default whatever after pipe or not.
and ack has no dangerous script breaking threat by that settings.

my grep settings like that in case of no ack somewhere:
```
alias grep='grep --color=always -i'
export  GREP_COLOR='7;33;34'
```
