### ISSUE TITLE
Perhaps .osx should be moved to its own repository

### ISSUE THREAD

**Issue by IvanMalison** [mathiasbynens/dotfiles#477]
It seems like one of the main things people use this repository for is its programatic configuration of MacOSX. it might make sense to move this configuration to a separate repository and make it more configurable/less opinionated so that people who don't use these dotfiles can still benefit from the work the community is doing on the programmatic configuration of OSX.

**Comment by maxiller** [comment]
Why just not to split on two branches? One for softheaded users and other for true geeks. Then merge majors discovers from one another.

**Comment by dstroot** [comment]
Wow! I just came here to suggest the same thing!   I have actually created a framework for this for my own use but I'd rather that Mathias endorse this approach and break out .osx into a separate repo and organize it better.  Check out my attempt: https://github.com/dstroot/.osx

Mathias - this would be a great new year's contribution to the community!

**Comment by oxyc** [comment]
#300

**Comment by nvartolomei** [comment]
I suggest to create a GUI tool that anyone could easily use and comes with defaults from .osx. Secondly those defaults could be changed (via GUI too) and stored in iCloud, Dropbox and GitHub. :)

**Comment by mathiasbynens** [comment]
Duplicate of #300.
