### ISSUE TITLE
Add .extra to .gitignore

### ISSUE THREAD

**Issue by icylace** [mathiasbynens/dotfiles#478]
Both your readme and and your .bash_profile suggests using .extra for settings you wouldn't want to commit.  Perhaps it's a good idea to reinforce this suggestion by including .extra in .gitignore ?

**Comment by mathiasbynens** [comment]
`.extra` would be located in your home directory, unlike the Git repository and its `.gitignore` — so I don’t see how that should help.

**Comment by icylace** [comment]
Ah, I see.  Thanks.
