### ISSUE TITLE
~/bin/bash is invalid

### ISSUE THREAD

**Issue by kongakong** [mathiasbynens/dotfiles#479]
Currently https://github.com/mathiasbynens/dotfiles/blob/master/bin/bash is a symlink to `/usr/local/Cellar/bash/4.2.45/bin/bash`. If brew installs a different version of bash, this symlink will become invalid. 

I think this file can be removed.

**Comment by chdiza** [comment]
Or it could be changed to point to `/usr/local/opt/bash/bin/bash`, which itself is a link to whatever happens to be both in-the-cellar and linked.  That would at least solve the problem of homebrew updating bash under one's nose.
