### ISSUE TITLE
What's the magic formula for AppleHighlightColor?

### ISSUE THREAD

**Issue by jreljac** [mathiasbynens/dotfiles#481]
I like the idea of a change but I'm not keen on the green.  How can I change the highlight color?  I realize "0.764700 0.976500 0.568600" is the green, I'm just not sure how to get the right values for another color.

**Comment by jreljac** [comment]
Disregard, I figured it out.

For those curious: 

Pick your desired color
Get that color's RGB values
Take each value and divide it by 255
Put them into the string in order R G B

The color 255,152,89 (RGB) would end up as:
defaults write NSGlobalDomain AppleHighlightColor -string "1 0.5960784314 0.3490196078"

**Comment by mathiasbynens** [comment]
Lame alternative: use the system preferences UI to pick any color you like, then read out its value using `defaults read`.

**Comment by jreljac** [comment]
@komarnicki It's been a few years but, IIRC, yes.  
`rgb(255,152,89)` = `1 0.5960784314 0.3490196078`
