### ISSUE TITLE
E185: Cannot find color scheme solarized

### ISSUE THREAD

**Issue by sensorario** [mathiasbynens/dotfiles#485]
$ vim acme/demo/file.php
Error detected while processing /Users/sensorario/.vimrc:
line    3:
E185: Cannot find color scheme solarized
Press ENTER or type command to continue

**Comment by dserodio** [comment]
Do you have Mathias' `.vim` symlinked or copied to your home dir, or only `.vimrc`?

**Comment by sensorario** [comment]
Mmmm very strange behavior: I've reinstalled this dotfiles. Now all works fine. I've just run

    $ sh ./bootstrap.sh
