### ISSUE TITLE
Does this work on Ubuntu or Linux Mint?

### ISSUE THREAD

**Issue by sergiotapia** [mathiasbynens/dotfiles#487]
I love using dotfiles and I have it installed on both my iMac and my macbook air.

However for work we're required to use Linux machines now, and I was wondering if this is usable on Linux. If not, do you recommend something similar that's just as ridiculously easy to install (with sensible defaults - I've never even had to customize this repo because it's so good).

Thank you!

**Comment by vicentebolea** [comment]
I made some sort of personal dotfiles for Linux based on this project. I took many things from this project, here is the link https://github.com/vicentebolea/dotfiles. :)

**Comment by nvartolomei** [comment]
@sergiotapia, everything will work, except .osx and home brew packages.

**Comment by jrahmy** [comment]
@sergiotapia Not necessarily. Some aliases and functions are OS X specific, and their Linux alternatives can vary by desktop environment and other factors.

The fundamentals like the bash prompt and vim config and such should work fine though.

**Comment by sergiotapia** [comment]
Sorry I should have been a bit clearer, I'm really only interested on the visual aspect of the addon. Such as showing the user name, folder path and feature branch name. 

@nvartolomei Does this mean that these things work on Linux?

**Comment by GarethLewin** [comment]
If all you are interested in is the prompt it should work, but dotfiles has so much more that you might want to consider forking and removing the unwanted stuff.

You might also want to take a look at some of the prompt specific options out there as they are more focues, I use https://github.com/nojhan/liquidprompt and I have used https://github.com/milkbikis/powerline-shell in the past, both support linux for sure.
