### ISSUE TITLE
`lscleanup` removes Share Menu options

### ISSUE THREAD

**Issue by dunn** [mathiasbynens/dotfiles#505]
It's meant to remove duplicate items from the "Open With" menu but it also removes (non-duplicate) items from the system share menu, at least on 10.10.2.

Before running `lscleanup`:

![screenshot 2015-02-28 21 29 00](https://cloud.githubusercontent.com/assets/985416/6429588/9379faac-bf91-11e4-9539-d02ebcd02b77.png)
![screenshot 2015-02-28 21 30 39](https://cloud.githubusercontent.com/assets/985416/6429589/9b680f6a-bf91-11e4-81f3-b80996f7c050.png)

After running `lscleanup`:

![screenshot 2015-02-28 21 31 28](https://cloud.githubusercontent.com/assets/985416/6429590/9e230322-bf91-11e4-80ab-696800d73749.png)
![screenshot 2015-02-28 21 31 39](https://cloud.githubusercontent.com/assets/985416/6429591/a0f8fd04-bf91-11e4-9d04-0b60edf9d60a.png)

They return after a restart so it's not a huge problem, and I'm not sure how the alias could be modified to avoid doing this while still performing its function.

**Comment by mathiasbynens** [comment]
> I'm not sure how the alias could be modified to avoid doing this while still performing its function.

I don’t think it can be.

A system reboot is required after running `.osx` anyway.
