### ISSUE TITLE
.osx: Disable the focus ring animation (10.10+)

### ISSUE THREAD

**Issue by oa-** [mathiasbynens/dotfiles#511]
.osx: `NSUseAnimatedFocusRing` disables the Focus ring animation

```
# disable the focus ring animation (10.10+)
defaults write -globalDomain NSUseAnimatedFocusRing -bool false
```

**Comment by mathiasbynens** [comment]
See <http://arstechnica.com/apple/2014/10/os-x-10-10/5/> for an example.

https://twitter.com/andrewe/status/563089874295984129/photo/1

**Comment by Tatsh** [comment]
Great tweak to have. Even though I rarely see it, I have hated this ever since I got Yosemite.

**Comment by chdiza** [comment]
This is great; I'd given up hope that this nonsense was disablable.

**Comment by oa-** [comment]
What about integrating this tweak into dotfiles/.osx ?
