### ISSUE TITLE
Send an email in Mail.app / not working

### ISSUE THREAD

**Issue by frdnrdb** [mathiasbynens/dotfiles#512]
I used to swiftly send mail via CMD+LSIFT+D. After 'defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"' i need to press the Send-icon manually. Really annoying. CMD+Enter does NOT work. Language/ International keyboard issue? Norwegian Keyboard here. Thanks!

**Comment by mathiasbynens** [comment]
Is your OS in English?

**Comment by frdnrdb** [comment]
yes! i found the answer via another issue, though; dbl dash was interpreted as quad dash. cmd+enter is now working (latest yosemite). but! what would i write (@/...) to restore cmd+shift+d. that shortcut is "part of me" ;-) thanks! 

Hilsen Frode

Den 17. mar. 2015 kl. 11.07 skrev Mathias Bynens <notifications@github.com>:

Is your OS in English?
