### ISSUE TITLE
Yosemite: Disturbing light blue "focus" outline around certain icons

### ISSUE THREAD

**Issue by frdnrdb** [mathiasbynens/dotfiles#514]
After i ran the .osx-bash several icons are affected, like these:

![image](https://cloud.githubusercontent.com/assets/81942/6777259/28c64ea4-d148-11e4-9c5a-17199b552169.png)

Any idea what line in the script that causes this?
Thanks!

**Comment by mathiasbynens** [comment]
My guess would be https://github.com/mathiasbynens/dotfiles/blob/98d67fca5c9f0448a5eb049e50f025b109dac5af/.osx#L170-L172.
