### ISSUE TITLE
Add Alias for git log

### ISSUE THREAD

**Issue by nikdatrix** [mathiasbynens/dotfiles#523]
```
alias lg="g log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias lgg="g log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
```

source (http://stackoverflow.com/questions/1057564/pretty-git-branch-graphs)

**Comment by mathiasbynens** [comment]
Thanks for the suggestion!

I’ll stick to https://github.com/mathiasbynens/dotfiles/blob/7552e009ae3451e152e126659f2e09870a0312d5/.gitconfig#L3-L4 for now. :)

**Comment by nikdatrix** [comment]
no problm, i just thought it was a little cooler :D

**Comment by hkdobrev** [comment]
@nikdatrix I've suggested some Git aliases here: https://github.com/mathiasbynens/dotfiles/pull/366 including a similar log. I hope you find something useful there.

**Comment by nikdatrix** [comment]
Thanks, Great stuff !
