### ISSUE TITLE
mac weird reboot loop, might be a homebrew package or dotfiles?

### ISSUE THREAD

**Issue by tejasmanohar** [mathiasbynens/dotfiles#530]
my dotfiles - https://github.com/tejasmanohar/dotfiles (brew.sh shows everything installed by `brew` and cask.sh by `brew cask`). my mac is facing a weird issue where i boot mac -> login -> it just "restarts"-ish where the apple logo shines in white/grey over black background again -> login again -> everything works. i bought it late last week so i'm guessing it's something i've installed / run while configuring the machine.

any advice? if this is irrelevant, just close the issue and let me know; my dotfiles are a fork of this and thus, i ask :)

**Comment by tejasmanohar** [comment]
https://www.dropbox.com/s/trzimojmfoztbni/20150426_131448.mp4?dl=0 - video of verbose boot
here's my console.app logs https://gist.github.com/tejasmanohar/149af7a6a395d776249a
maybe its stuff around l#5043?

**Comment by michahell** [comment]
I'm having the exact same issue. This is seriously bad, should never happen.

**Comment by tejasmanohar** [comment]
This is just FileVault :P

**Comment by michahell** [comment]
Really? :/ how / why / when / what did you do to solve this? I haven't been able to find a solution for this the past, say, 8 hours, and I've actually committed to a full fresh reinstall of OSX. well, fuck...

**Comment by tejasmanohar** [comment]
@michahell I didn't find a solution. This is how FileVault operates. It's not an error from what I can tell.
> my mac is facing a weird issue where i boot mac -> login -> it just "restarts"-ish where the apple logo shines in white/grey over black background again -> login again -> everything works.

**Comment by michahell** [comment]
Ah. I misread. I hada  different problem then, since in my case my mac KEPT restarting-ish... It never got past the login window. So something went wrong along the way.

**Comment by tejasmanohar** [comment]
Yea no clue about that sorry @michahell
