### ISSUE TITLE
Errors at terminal startup

### ISSUE THREAD

**Issue by tonioriol** [mathiasbynens/dotfiles#536]
Here is the output I see:
```bash
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```

![image](https://cloud.githubusercontent.com/assets/712937/7478861/e30c03e4-f35d-11e4-9379-9eb6f65c9633.png)

I just followed the tutorial steps on a Yosemite fresh install (the only step actually). Someone knows what else might cause this?

**Comment by leonklingele** [comment]
Your bash version seems to be outdated. `declare -A` declares a variable to be an associative array.
Bash supports associative array as of version 4.
So make sure `bash --version` gives you v4+.
If it doesn't, just install a newer bash version: `brew install bash`

**Comment by thibmaek** [comment]
Shouldn't `brew.sh` already do this automatically?
https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh#L28

**Comment by jrahmy** [comment]
```brew.sh``` installs a newer bash but doesn't set it up as your default shell

**Comment by vinkla** [comment]
Here is a article about [update Bash on Mac OS X](https://vinkla.com/posts/update-bash-mac-osx/).

**Comment by tonioriol** [comment]
That's what was wrong @leonklingele. Solved following the steps that @vinkla was referring. Thank you all.

As @jrahmy says, it is not done by the script. But I think it should be done automatically.

**Comment by s10wen** [comment]
@vinkla I'm also getting this error, looks like your link has moved? It's redirecting to https://vinkla.com/ is the original post online anywhere?

**Comment by erquhart** [comment]
For anyone else that winds up here, here's a different blog with the proper steps: 
http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/

In most cases, the relevant excerpt is this right here:
```shell
# Add the new shell to the list of allowed shells
sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
# Change to the new shell
chsh -s /usr/local/bin/bash 
```

**Comment by s10wen** [comment]
Thanks @erquhart I managed to fix this, but wasn't sure exactly how! If I encounter it again I'll try this out and report back.
