### ISSUE TITLE
bash error

### ISSUE THREAD

**Issue by maxigor** [mathiasbynens/dotfiles#539]
Hey guys, every time I open the terminal I get this message: 

> -bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]

Does anyone have any idea what it might be?

**Comment by mathiasbynens** [comment]
See #536.
