### ISSUE TITLE
Default app to open all files of particular file type

### ISSUE THREAD

**Issue by necolas** [mathiasbynens/dotfiles#54]
I've been looking for ways to control which app is the default to open certain file types. This way, when I install my dotfiles on another machine I don't have to use Finder to change the default app used to open `.html`, `.css`, etc., files when opened from Finder...that would be a real PITA.

Here are a couple of promising links:

http://superuser.com/questions/20822/where-does-mac-os-x-store-file-association-information
http://superuser.com/questions/273756/how-to-change-default-app-for-all-files-of-particular-file-type-through-terminal

With your superior `defaults write`-fu, you might find the solution (or lack of) sooner than me.

**Comment by briancrink** [comment]
with [duti](https://github.com/moretension/duti/issues/33), is there support for dotfiles?
