### ISSUE TITLE
.osx: `defaults write NSGlobalDomain KeyRepeat -int 0` no longer works

### ISSUE THREAD

**Issue by dunn** [mathiasbynens/dotfiles#540]
I just noticed this today; maybe it happened with the 10.10.3 update. But the repeat-rate is no longer blazingly fast:

![osx](https://cloud.githubusercontent.com/assets/985416/7551623/16fba8b4-f645-11e4-95e8-b410ed890573.gif)

**Comment by vinkla** [comment]
@dunn Have you tried restarting your computer after running the `.osx` script? That worked for me.

**Comment by dunn** [comment]
I rebooted a second time and it's working. Weird.

**Comment by vinkla** [comment]
:+1:
