### ISSUE TITLE
Bash prompt gets overwritten on long commands

### ISSUE THREAD

**Issue by danielmanser** [mathiasbynens/dotfiles#547]
Hi

Thanks for sharing your great dotfiles. I'm using it as a great inspiration source. In fact, I've taken your .bash_prompt settings for my Mac OS X Yosemite machine. I noticed that the command line gets overwritten when I type long command lines. Is this something that's related to my setup only or do you experience this as well?

I'm trying to find a solution for this (i.e. wrapping it to the new line). I noticed it seems to be relative to the Terminal window (I'm using iTerm2). Any ideas?

**Comment by mathiasbynens** [comment]
#537
