### ISSUE TITLE
tab in terminal spits out new line

### ISSUE THREAD

**Issue by elgubenis** [mathiasbynens/dotfiles#552]
hi, when im tabbing for file/command completion in the terminal, on every tab a new line is generated, is that a desired behavior? see example attached.
![screen shot 2015-06-22 at 12 53 01](https://cloud.githubusercontent.com/assets/7453396/8288750/a2b5d842-18dd-11e5-91cb-f870fbc4db54.png)

**Comment by mathiasbynens** [comment]
Yes. If there are multiple completion suggestions it will list them there.
