### ISSUE TITLE
Terminal showing a blank screen

### ISSUE THREAD

**Issue by dzt** [mathiasbynens/dotfiles#560]
After Installing this my Terminal all of a sudden became faulty. 

It shows a blank screen, and when I end the git process in Activity Monitor I get stuck at this screen all of a sudden.

![screen shot 2015-07-23 at 1 33 09 pm](https://cloud.githubusercontent.com/assets/6421443/8857396/678a55ac-313f-11e5-81bd-643be4dfec39.png)

**Comment by mathiasbynens** [comment]
…Did you make your entire home folder a git repository? :fearful:

**Comment by mathiasbynens** [comment]
Follow https://github.com/mathiasbynens/dotfiles#installation next time.

**Comment by dzt** [comment]
What should I do now?

**Comment by mathiasbynens** [comment]
That depends on what exactly you did in the first place. `rm -rf ~/.git` would be a start.

**Comment by dzt** [comment]
I did the whole installation process from my user directory.

**Comment by dzt** [comment]
``` rm -rf ~/.git ``` just saved me
