### ISSUE TITLE
How do I change the colours?

### ISSUE THREAD

**Issue by robertdefilippi** [mathiasbynens/dotfiles#567]
I don't know if this is an issue, but can you change the default colour for dotfiles?

**Comment by AlecRust** [comment]
@chef1075 the default colour of what exactly?

**Comment by Tatsh** [comment]
Well:

Highlight colour: https://github.com/mathiasbynens/dotfiles/blob/master/.osx#L43

Bash PS1, etc: https://github.com/mathiasbynens/dotfiles/blob/master/.osx#L43
