### ISSUE TITLE
After running ./brew.sh the bashrc is somewhat broken

### ISSUE THREAD

**Issue by natrixnatrix89** [mathiasbynens/dotfiles#569]
It appears after installing the newest packages listed in ./brew.sh the installed bash version no longer supports the API called in some of the files linked from bashrc.

As a result a newly opened terminal will open with the following errors:
```
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]

user at Users-iMac in ~
```

Also the completion is broken when pressing the tab key.

**Comment by AlecRust** [comment]
See https://github.com/mathiasbynens/dotfiles/issues/544

**Comment by natrixnatrix89** [comment]
Thank you! Sorry for duplicate issue.
But anyhow.. the 2 lines suggested should be added to the brew sh script, if it detects that the bash version doesn't match.
