### ISSUE TITLE
Setting up Sublime Text

### ISSUE THREAD

**Issue by s10wen** [mathiasbynens/dotfiles#570]
I recently ran my [dotfiles](https://github.com/s10wen/dotfiles/) (which was mainly absolutely awesome) and now I'm going through tidying a few things up.

One thing I like to do is setup Sublime Text by adding a few files that include preferences, key bindings and snippets. The way I've previously done this is by having the files in the dotfiles repo then copying them as part of the `.osx` file run, e.g.:
```
cp init/console_log.sublime-snippet ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/
```

But when I ran my `.osx` file I didn't have Sublime Text installed and thus the path didn't exist and I got an error. I'm thinking a better way would be to use `curl` and link to a gist instead.
```
curl -o ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Emmet.sublime-settings https://gist.githubusercontent.com/s10wen/b2c839e725965ad11c1f/raw/ff6153621974787430f9b58bd2e965e16e2ddb7d/gistfile1.txt
```

Wondering what people think to this approach, or if there's maybe a better way to go about doing this entirely?

**Comment by GarethLewin** [comment]
`mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/`

**Comment by s10wen** [comment]
Thanks @GarethLewin I believe it's also possible to do:
```
curl --create-dirs -o ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Emmet.sublime-settings https://gist.githubusercontent.com/s10wen/b2c839e725965ad11c1f/raw/ff6153621974787430f9b58bd2e965e16e2ddb7d/gistfile1.txt
```
