### ISSUE TITLE
Add a warning message to this repo

### ISSUE THREAD

**Issue by guerrero** [mathiasbynens/dotfiles#576]
It would be nice to add a warning message about possible consequences of the use of this repo modified or in an environment different than that used by the owner. I can create a PR but, firstly, I want to know if this seems good to @mathiasbynens

Related to this topic: #530 #575

**Comment by mathiasbynens** [comment]
Added: https://github.com/mathiasbynens/dotfiles#installation

**Comment by guerrero** [comment]
Great! :ok_hand:
