### ISSUE TITLE
How to Prevent Overwriting git config when using bootstrap.sh?

### ISSUE THREAD

**Issue by surfer190** [mathiasbynens/dotfiles#581]
Hi

How do you prevent the overwriting of `git config` when running

```
bash bootstrap.sh
```

**Comment by GarethLewin** [comment]
You can't, that isn't what this repo is about. It's bootstrapping Mathias's user's gitconfig.

You could do something like
```
cp ~/.gitconfig /tmp
bash bootstrap.sh
cp /tmp/.gitconfig ~
```

But really I recommend spending time and reading what this repo gives you / does before using it, bootstrap.sh does warn you it's going to do stuff you might not like.

**Comment by surfer190** [comment]
@GarethLewin 

`It's bootstrapping Mathias's user's gitconfig`

Are you sure? In my case it clears the `.gitconfig`. Which means that when you are customising the dotfiles and then run `bash bootstrap.sh` to test it out. You can't commit because it requests the git username and email.

Not a good workflow for changing and testing the repo.
Can you suggest a way that makes it easy to work on?

**Comment by mathiasbynens** [comment]
@surfer190 You could add an `--exclude` entry here: https://github.com/mathiasbynens/dotfiles/blob/9e09c6a0dacd297d46dd3988f2ce8b7281d8e318/bootstrap.sh#L8-L9
