### ISSUE TITLE
Are coreutils still outdated in El Capitan?

### ISSUE THREAD

**Issue by kevinSuttle** [mathiasbynens/dotfiles#584]
https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh#L19

**Comment by nvartolomei** [comment]
I think you can't even check what version of coreutils are built-in into OS X. I will continue to use coreutils provided by homebrew because of compatibility.

**Comment by mathiasbynens** [comment]
Yeah, and they always will be due to licensing issues IIRC. Same with the built-in `bash` version.
