### ISSUE TITLE
Tiny typo in .osx

### ISSUE THREAD

**Issue by Alhadis** [mathiasbynens/dotfiles#592]
[Line 519](https://github.com/mathiasbynens/dotfiles/blob/master/.osx#L519)

>  Yosemite-specific search results (remove them if **your are**

Guessing that's obviously meant to be "you're" or "you are", heh.

**Comment by mathiasbynens** [comment]
Thanks!

**Comment by Alhadis** [comment]
Geen dank. :) Good shit, BTW. Very useful.
