### ISSUE TITLE
Bash invalid option error

### ISSUE THREAD

**Issue by karthilxg** [mathiasbynens/dotfiles#595]
Forked repo: https://github.com/karthilxg/dotfiles/

I'm getting the below message everytime when I open a new terminal window.

```bash
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```

And filename completion shows message as 'command not found' while changing directory and pressing enter key takes to the respective folder (Not sure this is expected) for example when I type `cd ini` at first it displays the below message and takes to the `init` folder

```bash
$ ls
CREDITS.md   LICENSE.txt  README.md    bin          bootstrap.sh brew.sh      init         osx.sh       osxprep.sh   web.sh
$ cd ini-bash: compopt: command not found
t
$ pwd
/Users/karthi_thangaraj/Documents/Git-public/dotfiles/init
```

**Environment:**

`OS X El Captian Version 10.11.1 (15B42)`
`Terminal Version 2.6 (361)`

```sh
echo $BASH_VERSION
3.2.57(1)-release
```

```sh
bash -version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by cemo** [comment]
Duplicates #544

**Comment by karthilxg** [comment]
Thanks @cemo 

Followed the steps as mentioned in this article resolves the issue [updating Bash on Mac OS X](https://vinkla.com/posts/update-bash-mac-osx/).

**Comment by cemo** [comment]
You're welcome. Don't forget to close issue. :)
