### ISSUE TITLE
Square bracket added to front of prompt of previous command

### ISSUE THREAD

**Issue by plinto** [mathiasbynens/dotfiles#599]
A square bracket appears at the front of the prompt of the previously executed command. I've only noticed this since I updated to OS X 10.11.1

<img width="481" alt="screen shot 2015-11-05 at 9 31 06 pm" src="https://cloud.githubusercontent.com/assets/1543921/10980882/a0715362-8404-11e5-9607-1773aa4c701e.png">

**Comment by amalucelli** [comment]
Hi @plinto, try to disable "Automatically Mark Prompt Lines" from Terminal, like this http://superuser.com/a/975295

**Comment by plinto** [comment]
Thanks @amalucelli, that solved it
