### ISSUE TITLE
How to change wallpaper in El Capitan?

### ISSUE THREAD

**Issue by kud** [mathiasbynens/dotfiles#602]
Since SIP, you can't do that: https://github.com/kud/my/blob/master/core/osx#L134-L138

Do you have any other way to do that?

**Comment by reitermarkus** [comment]
I just added this to my dotfiles a few days ago:

https://github.com/reitermarkus/dotfiles/blob/master/include/8.0-defaults_dock_finder.sh#L104-L105

**Comment by kud** [comment]
Thanks, I will have a try.

**Comment by sindresorhus** [comment]
You could use https://github.com/sindresorhus/osx-wallpaper.

**Comment by kud** [comment]
Thank you @sindresorhus

**Comment by mathiasbynens** [comment]
Closing as the question has been answered twice.

**Comment by kud** [comment]
The first one didn't work for me. The second one only works on the current desktop, not every desktop you could have.

**Comment by reitermarkus** [comment]
Did you `killall cfprefsd Dock` after `sqlite3 "${HOME}/Library/Application Support/Dock/desktoppicture.db" "update data set value = '/path/to/picture.png'"`?

**Comment by kud** [comment]
Even with `killall Dock`, it doesn't work.

`$ wallpaper` works though but needs to be applied on every desktop.
