### ISSUE TITLE
⌘ + Enter to send in Mail.app does not work under El Capitan

### ISSUE THREAD

**Issue by mathiasjakobsen** [mathiasbynens/dotfiles#603]
One of my favorite features of ``.osx`` is the quick send feature enabled in Mail.app.
But it's not working if I execute it under El Capitan.

Reference: https://github.com/mathiasbynens/dotfiles/blob/7d43ff6f8f07b31b514b17b776304ef4864cf9c5/.osx#L492

**Comment by mathiasbynens** [comment]
Why was this closed?

**Comment by mathiasbynens** [comment]
Why was this closed?

**Comment by mathiasjakobsen** [comment]
I made a Pull Request that fixes the problem, instead.

https://github.com/mathiasbynens/dotfiles/pull/661
