### ISSUE TITLE
Tab complete -bash: compopt: command not found - Yosemite 10.10.5

### ISSUE THREAD

**Issue by Ryahn** [mathiasbynens/dotfiles#605]
When ever I try to tab complete on anything, programs, directories, etc. Bash will throw the following error
```bash
-bash: compopt: command not found
```

Even though it throws that error, if you know the tab completion is correct, you can hit enter and it will go to it. Before I used dotfiles, I never had this issue before.

**Comment by cemo** [comment]
probably same as #544

**Comment by Ryahn** [comment]
That did the trick. Thank you @cemo
