### ISSUE TITLE
Do you want to close this window?

### ISSUE THREAD

**Issue by Moeriki** [mathiasbynens/dotfiles#618]
![image](https://cloud.githubusercontent.com/assets/38758/12379693/58817322-bd5f-11e5-9ab5-23fa4c74daf0.png)

OS X terminal asks "Do you want to close this window?" on CMD + W. Can't find how to disable it.

In settings > profiles > [my profile] > Shell I set the following settings.

![image](https://cloud.githubusercontent.com/assets/38758/12379700/74e45002-bd5f-11e5-8ee7-c45f430223fd.png)

Anyone know how to resolve this? Thanks a lot for your suggestions!

**Comment by jrahmy** [comment]
Remove all the bash lines from that setting?

The setting *will* prompt on closing if any of the programs listed are currently running.

**Comment by Moeriki** [comment]
That's not how I understand this menu. Either way the default is without all of these entries (just tmux and screen). I just tried it again. Doesn't work.

AFAIK Terminal will prompt if any process is running, other than the ones listed.

**Comment by jrahmy** [comment]
Oops. I misread. You're right, sorry.

**Comment by mathiasbynens** [comment]
Closing as it’s not related to this repository. (I use iTerm 2, FWIW.)
