### ISSUE TITLE
.osx: chmod error

### ISSUE THREAD

**Issue by s10wen** [mathiasbynens/dotfiles#619]
Just got this when running my `.osx` file, wondering if anyone else has had this?

```
chmod: Unable to change file mode on /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search: Operation not permitted
```

**Comment by mathiasbynens** [comment]
Is that in relation to this line (i.e. did you uncomment this)?

https://github.com/mathiasbynens/dotfiles/blob/e7ef66da4f6a077261286df3729d823a1d39e04b/.osx#L516-L517

**Comment by s10wen** [comment]
Cheers @mathiasbynens looks like I have some updates to make!
