### ISSUE TITLE
Homebrew is designed to work without using sudo. 

### ISSUE THREAD

**Issue by Bernd-HAL** [mathiasbynens/dotfiles#620]
Homebrew is designed to work without using sudo. You can decide to use it but we strongly recommend not to do so. If you have used sudo and run into a bug then it is likely to be the cause. Please don’t file a bug report unless you can reproduce it after reinstalling Homebrew from scratch without using sudo

!/usr/bin/env bash

Install command-line tools using Homebrew.

Ask for the administrator password upfront.
sudo -v

**Comment by mathiasbynens** [comment]
What were you trying to do? None of my dotfiles contain `sudo brew`.
