### ISSUE TITLE
When I use tab in autocompleting the folder name

### ISSUE THREAD

**Issue by gideonaire** [mathiasbynens/dotfiles#639]
Im using 10.11.3 OS X El Capitan after I run ```.osx``` I encountered a problem ```cd -bash: compopt: command not found``` Is there something Im missing. This is a fresh install El capitan.

**Comment by GarethLewin** [comment]
https://github.com/mathiasbynens/dotfiles/issues/544

**Comment by gideonaire** [comment]
@GarethLewin Thank a lot man!
