### ISSUE TITLE
Opening new terminal

### ISSUE THREAD

**Issue by gideonaire** [mathiasbynens/dotfiles#640]
When opening up a new terminal this is what it shows. Im using 10.11.3 OS X El Capitan. Is there something Im missing?
<img width="1425" alt="screen shot 2016-03-13 at 06 31 53" src="https://cloud.githubusercontent.com/assets/17807377/13727219/1a9f8880-e8ea-11e5-9a90-0d628eeab544.png">

**Comment by GarethLewin** [comment]
https://github.com/mathiasbynens/dotfiles/issues/536

**Comment by gideonaire** [comment]
@GarethLewin wow thanks works like magic!
