### ISSUE TITLE
unexpected EOF while looking for matching ``'

### ISSUE THREAD

**Issue by s10wen** [mathiasbynens/dotfiles#641]
Weird, just started getting this;
```
-bash: /Users/s10wen/.bash_profile: line 47: unexpected EOF while looking for matching ``'
-bash: /Users/s10wen/.bash_profile: line 64: syntax error: unexpected end of file
```

**Comment by mathiasbynens** [comment]
What’s on those lines?

**Comment by s10wen** [comment]
`# Add `killall` tab completion for common apps` then it errors on another line with similar comments.

**Comment by mathiasbynens** [comment]
Unrelated to the problem, but that sounds like an `.osx` command — why would you want that to be in your `.bash_profile`?

**Comment by s10wen** [comment]
Sorry @mathiasbynens looks like somehow I'd managed to get backtick as the first character of the file, that was causing the issue, no idea how it got there though :rabbit:

**Comment by s10wen** [comment]
```
