### ISSUE TITLE
Can't commit after installing dotfiles

### ISSUE THREAD

**Issue by Darvile** [mathiasbynens/dotfiles#649]
Hi guys after installing dotfiles I'm not able to commit changes.
I'm getting this when I run git commit.
`git commit -m "Initial commit"
error: cannot run gpg: No such file or directory
error: could not run gpg.
fatal: failed to write commit object`

Can anyone help me out?

**Comment by Tatsh** [comment]
You do not have GPG installed. I would highly recommend getting started with that. https://help.github.com/articles/signing-commits-using-gpg/

You can disable it:

```bash
git config --global commit.gpgsign false
```

**Comment by Darvile** [comment]
Thanks @Tatsh that did the trick!
I will checkout on the docs later.
