### ISSUE TITLE
Error with declare

### ISSUE THREAD

**Issue by neposoft** [mathiasbynens/dotfiles#663]
I get a error when I start my bash terminal.
Here is what i get:

` -bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]`

**Comment by GarethLewin** [comment]
This is a frequently asked question, I recommend searching issues of OSS projects, just in case the question has been asked before, for example "https://github.com/mathiasbynens/dotfiles/issues?utf8=%E2%9C%93&q=invalid+option+declare"

https://github.com/mathiasbynens/dotfiles/issues/536
