### ISSUE TITLE
Simplify Custom Terminal Theme

### ISSUE THREAD

**Issue by alycda** [mathiasbynens/dotfiles#665]
Hi, I think there is a more concise way to do [this](https://github.com/mathiasbynens/dotfiles/blob/40fd8cc726742f5d152afc5dc99aab1f8ac4c888/.osx#L567-L612)

```shell
# open the custom theme so it gets added to the list
open "$HOME/.settings/Solarized Dark Alyda.terminal"
# wait for 5 seconds to make sure custom theme was added
sleep 5
# set custom theme
defaults write com.apple.Terminal "Default Window Settings" -string "Solarized Dark Alyda"
defaults write com.apple.Terminal "Startup Window Settings" -string "Solarized Dark Alyda"
```

I tried a 1 second wait and it did not work so I upped it to 5. 3 is probably good but I didn't feel like playing with it.

Figured out some of it on my own and from [this guy](https://www.skrauth.de/blog/2015/osx-settings-via-terminal/).

**Comment by mathiasbynens** [comment]
This is exactly what I used before I switched to the current code in 1f6ead4fca779e498672a39403aa6926280fdfa0 (#492).

**Comment by alycda** [comment]
Sorry, didn't see that.
