### ISSUE TITLE
'afk' causes system freakout

### ISSUE THREAD

**Issue by disconn3ct** [mathiasbynens/dotfiles#667]
On El Capitan, the afk alias results in a popup that says (paraphrase, unfortunately) "Security center can only be called by apple applications". It just keeps cycling over a black screen and cannot be effectively closed. (I ended up rebooting, but it is possible remote access could have been used.)

**Comment by mathiasbynens** [comment]
Works fine here on 10.11.4 (15E65).

**Comment by disconn3ct** [comment]
10.11.5 (15F34)

I can retest this evening and get the exact popup text.

**Comment by Tatsh** [comment]
This message usually appears after a system update and before rebooting. Reboot and everything should be fine.
