### ISSUE TITLE
add npm-debug.log to gitignore?

### ISSUE THREAD

**Issue by stevemao** [mathiasbynens/dotfiles#669]
Seems pretty common. 
Also it looks like this is missing some other common files to ignore.

**Comment by hkdobrev** [comment]
See https://help.github.com/articles/ignoring-files/ and the suggested global gitignore: https://gist.github.com/octocat/9257657 It includes `*.log` which would cover this.

I'm not saying `npm-debug.log` should never be ignored in a project `.gitignore`, but it shouldn't normally be the case for non-npm repositories like this one.

**Comment by stevemao** [comment]
I'm good to add `*.log` then.

**Comment by mathiasbynens** [comment]
I’d rather not ignore `npm-debug.log` or `*.log` by default.
