### ISSUE TITLE
./.osx issue

### ISSUE THREAD

**Issue by mayank-ism** [mathiasbynens/dotfiles#672]
Is there any way I can go back to my previous setting?

**Comment by jrahmy** [comment]
Not really, other than restoring from a backup or changing them back individually one by one.

**Comment by ohblue** [comment]
and how do  i know the default setting for OSX ...

**Comment by guerrero** [comment]
@mayank-ism see #58 :)

**Comment by tarkanlar** [comment]
Oh it looks like we need to delete everything and reinstall osx to get rid of this?
