### ISSUE TITLE
Add an .editorconfig

### ISSUE THREAD

**Issue by davidhund** [mathiasbynens/dotfiles#69]
Maybe an `.editorconfig` file would be a good addition?

From: http://editorconfig.org/

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.
> The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins 
> that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readibly and
> they work nicely with version control systems.

**Comment by SimonSchick** [comment]
Can't this be closed since the file has been added?

**Comment by mathiasbynens** [comment]
@SimonSchick Good call.
