### ISSUE TITLE
Global function variables

### ISSUE THREAD

**Issue by artemgurzhii** [mathiasbynens/dotfiles#694]
In `.functions` file peferred to use 
```shell
mkd() {
  mkdir -p "$@" && cd "$_";
}
```
instead of
```shell
function mkd() {
  mkdir -p "$@" && cd "$_";
}
```
to avoid unnecessary global variables.

**Comment by mathiasbynens** [comment]
Which variables are globally created in example 1 vs. example 2?

**Comment by artemgurzhii** [comment]
[Bash style guide](https://github.com/bahamas10/bash-style-guide#functions). Not on this example. I choose this one because this is the shortest function. This is kind of the best practice to use `sum()` instead of `function sum()`, so if you created the variable inside a function, and forget to add local, it's not going to cause any problems. Plus easier to read.

**Comment by mathiasbynens** [comment]
`function foo() {}` vs. `foo() {}` is a personal preference that doesn’t have any impact on which variables become global.

```sh
$ unset i; echo "Before: ${i}"; function foo() { i=42; }; foo; echo "After: ${i}";
Before:
After: 42

$ unset i; echo "Before: ${i}"; foo() { i=42; }; foo; echo "After: ${i}";
Before:
After: 42
```

I prefer `function` so I’ll stick with that.
