### ISSUE TITLE
.macos broke Chrome gestures

### ISSUE THREAD

**Issue by robbens** [mathiasbynens/dotfiles#700]
So I just did a fresh install with El Capitan. After I ran the .macos file and restarted the computer, the gestures(swipe back and forward through pages) isn't working. 
I had the same issue on my last install which was very annoying.

How do I fix this?

**Comment by robbens** [comment]
Well, shame on me. I found it. **AppleEnableSwipeNavigateWithScrolls**

For you future readers. Just copy the selected code and change `false` to `true`

https://github.com/mathiasbynens/dotfiles/blob/master/.macos#L770-L776

**Comment by colinbrislawn** [comment]
@robbens Thank you for posting this! I also had this issue and appreciate that you took the time to show how to fix it.
