### ISSUE TITLE
[URGENT] [IMPORTANT] GPG Issue?

### ISSUE THREAD

**Issue by OktayGardener** [mathiasbynens/dotfiles#724]
git commit -m "hello"

error: cannot run gpg: No such file or directory
error: could not run gpg.
fatal: failed to write commit object

What is this and how do I get rid of this?

No, installing GPG won't help.
Yes, reformatting my computer was the only option after getting stuck with this for countless of hours.

Happens with OS X 10.12 Sierra after executing the following

git clone https://github.com/mathiasbynens/dotfiles.git && cd dotfiles && source bootstrap.sh

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/dotfiles/blob/2f0d5d65a87765875c3af71e258bd3e7b045b5eb/.gitconfig#L128-L131

Please do as the README says and fork/check/modify these dotfiles before installing them on your own system.

**Comment by OktayGardener** [comment]
BLESS
