### ISSUE TITLE
Bash completion does not work on fresh macOS 10.12 and brew.sh install

### ISSUE THREAD

**Issue by HanSooloo** [mathiasbynens/dotfiles#725]
I cannot get bash-completion to work with default install of dotfiles.  

```.bash_profile``` script is trying to source the ```bash_completion``` file at ```$(brew --prefix)/share/bash-completion/bash_completion```.

However, brew does NOT install bash-completion there.  Instead, the correct location is ```$(brew --prefix)/etc/bash_completion```

**Steps to reproduce:**
1. Install macOS 10.12 (latest)
1. Install brewh.sh: ```/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"```
1. Install bash-completion: ```brew install bash-completion```
1. Open a new terminal
1. ```dd ```, press Tab twice for completion options

**Observed results:**
1. No completion options shown for `dd` command, which should include things like ```if=``` or ```of=```

**Expected results:** 
1. Completion options should be shown
```$ dd
--help     bs=        conv=      ibs=       obs=       seek=
--version  cbs=       count=     if=        of=        skip=
```

**Suggested fix:**
Use ```$(brew --prefix)/etc/bash_completion``` in ```.bash_profile```
#https://github.com/HanSooloo/dotfiles/pull/1

**Comment by mathiasbynens** [comment]
bash-completion is for Bash 3, which is the default on macOS.

My dotfiles install `bash-completion2` (for Bash 4) along with Bash 4 when running `brew.sh`: https://github.com/mathiasbynens/dotfiles/blob/ade45bde0b30ac7adc599cb6ddeb4674f8e0e0d5/brew.sh#L26
