### ISSUE TITLE
use m-cli instead of manually defaults-writing

### ISSUE THREAD

**Issue by thegranddesign** [mathiasbynens/dotfiles#748]
@mathiasbynens I have come back to your `.macos` dotfiles regularly for years to see whether new versions of macOS have changed/broken some of my beloved `defaults write` commands before I actually install the OS.  Unfortunately I need to go to about 9 different repos to get a good handle on it, and even then it doesn't cover everything.

The reason is that, for these commands, there is no "one place" to compile all of the information about them.  So knowledge is strewn all over the internet.

I've spent the last three days converting all of my scripts and `defaults write` commands over to `m-cli`.  I feel as though, due to its popularity and the fact that it's "just bash", `m-cli` is a perfect place for us to begin to consolidate this information.

Please take a look at [my PR](https://github.com/rgcr/m-cli/pull/102) and I think you'll see that this is a vastly superior solution to what we've been doing for the last 5 years.

**Comment by mathiasbynens** [comment]
> The reason is that, for these commands, there is no "one place" to compile all of the information about them. So knowledge is strewn all over the internet.

Isn’t this repository the one place? It sure is for me.

**Comment by mathiasbynens** [comment]
I hadn’t heard of m-cli before. Thanks for the suggestion — I’ll think about it!

**Comment by thegranddesign** [comment]
@mathiasbynens 

> Isn’t this repository the one place? It sure is for me.

Well yeah, that's because they're _your_ dotfiles. 😂

For other people they may not want your dotfiles, but they come here looking for whether certain `defaults write` commands are breaking.  I doubt very strongly that someone just takes your `.macos` file and runs it without any changes.

By moving the _how_ that a thing gets done (say autohiding the dock) from the _whether_ something gets done (dotfiles) allows everyone to be able to customize their dotfiles however they'd like without worrying about the "how".
