### ISSUE TITLE
Dock stacks no longer persist

### ISSUE THREAD

**Issue by bensleveritt** [mathiasbynens/dotfiles#750]
I'm not entirely sure what's happened, but whenever the dock is restarted the stacks are gone. This is on a new installation of Sierra.

Any ideas?

**Comment by bensleveritt** [comment]
Nevermind, just blanket deleted my prefs for the Dock and started again.
`defaults delete com.apple.dock; killall Dock`

**Comment by bensleveritt** [comment]
Okay, so one of the dock commands causes the Dock to forget its layout on restart. Not sure which yet.

**Comment by mathiasbynens** [comment]
Hmm, I can’t seem to reproduce this issue. Feel free to reopen with reproduction steps.
