### ISSUE TITLE
Waiting to update Sierra

### ISSUE THREAD

**Issue by GertJVD** [mathiasbynens/dotfiles#759]
Thanks for trying to fix this problem. I get keys not responding and gibberish on others after the latest Sierra update. Mine is an older machine so maybe its just peculiar/particular. Should I just wait for 6 months to see if Apple has fixed the update?

**Comment by mathiasbynens** [comment]
It’s unclear what you’re referring to exactly. Either way, this is not a support forum — try [Ask Different](https://apple.stackexchange.com/) for that.
