### ISSUE TITLE
error with command in `emptytrash` alias

### ISSUE THREAD

**Issue by erikrtn** [mathiasbynens/dotfiles#762]
This works in my terminal:

```
sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2 'select LSQuarantineDataURLString from LSQuarantineEvent'
```

But this command does not; note the database file is now `V*`:

```
sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'select LSQuarantineDataURLString from LSQuarantineEvent'
```

I get this error message:

```
Error: near "/": syntax error
```

Google and StackOverflow searches revealed no help.

**Comment by Tatsh** [comment]
I am guessing you have multiple files that match `~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV*`. The expectation is exactly one. The second one is getting interpreted as a SQLite command.

**Comment by erikrtn** [comment]
In `~/Library/Preferences`, I have both:

```
com.apple.LaunchServices.QuarantineEventsV*
com.apple.LaunchServices.QuarantineEventsV2
```

I deleted `com.apple.LaunchServices.QuarantineEventsV*` which is not the most sophisticated way of solving this problem but now it is fine.
