### ISSUE TITLE
Merge outstanding PRs

### ISSUE THREAD

**Issue by hassankhan** [mathiasbynens/dotfiles#763]
Hi @mathiasbynens, was just wondering if you'll be merging any of these PRs soon?:

https://github.com/mathiasbynens/dotfiles/pull/755
https://github.com/mathiasbynens/dotfiles/pull/751
https://github.com/mathiasbynens/dotfiles/pull/742

**Comment by mathiasbynens** [comment]
The fact that a PR is open is a reminder to me to review it and possibly merge it. Please don’t create issues to remind me of those reminders 😞

**Comment by hassankhan** [comment]
Apologies, was just a bit impatient 😄
