### ISSUE TITLE
git can't sign

### ISSUE THREAD

**Issue by chb0github** [mathiasbynens/dotfiles#789]
I love the terminal but now git signing is broke:

```
 git commit -am "Remove integration test config"
error: gpg failed to sign the data
fatal: failed to write commit object

```

I know: Caveat emptor. Just wanna know if you have a simple fix. Otherwise I must remove :-/

**Comment by kievu** [comment]
Had the same issues and found it is was my own fault. It already says in README 

> Warning: If you want to give these dotfiles a try, you should first fork this repository, review the code, and remove things you don’t want or need. Don’t blindly use my settings unless you know what that entails. Use at your own risk!

So I searched and found out that in .gitconfig

`# https://help.github.com/articles/signing-commits-using-gpg/
	gpgsign = true`

And I don't use gpg keys so what I did was:

`git config --global commit.gpgsign false`
