### ISSUE TITLE
add support for ATOM texteditor

### ISSUE THREAD

**Issue by SiNaPsEr0x** [mathiasbynens/dotfiles#791]
please add support extensions for this application

**Comment by mathiasbynens** [comment]
???

**Comment by SiNaPsEr0x** [comment]
aliases for sublime text is .s ... can add .a for ATOM ?

**Comment by mathiasbynens** [comment]
I don’t use Atom. But sure, you could add these aliases in your own fork.

**Comment by SiNaPsEr0x** [comment]
scuse me... atom is alredy integrated

**Comment by mathiasbynens** [comment]
Oh, right: https://github.com/mathiasbynens/dotfiles/blob/7657dc538a2fda0f2dd8a603bbb957b1d0b490c5/.functions#L200-L208 Thanks for reminding me to remove that :)

**Comment by SiNaPsEr0x** [comment]
why removed??? its fantastic...
