### ISSUE TITLE
Spectacle settings are now moved under Library > Application Support

### ISSUE THREAD

**Issue by ricklancee** [mathiasbynens/dotfiles#798]
Hi! I was trying to configure my own spectacle settings with [this script here](https://github.com/mathiasbynens/dotfiles/issues/507) only to find out the settings are no longer written in the `.plist` file but under Application Support in a `.json` file.  (see: https://github.com/eczarny/spectacle/issues/424)

They can now be found here: `~/Library/Application\ Support/Spectacle/Shortcuts.json`

Maybe add the settings in the `init/` folder and copy them to the `Application\ Support/Spectacle/` directory?

In the `.macos` file i added:
```
cp "$HOME/init/Shortcuts.json" "$HOME/Library/Application Support/Spectacle/Shortcuts.json"
```

I would create a PR but i don't know what settings you are using for Spectacle.

**Comment by mathiasbynens** [comment]
Thanks!
