### ISSUE TITLE
.osx has removed safari icons + other system ui icons

### ISSUE THREAD

**Issue by 1gitGrey** [mathiasbynens/dotfiles#805]
the .osx file in the repository needs like some warnings it seems to have done irrversible damage to a lot of things including my icons and now notification center doesnt work at all even with running the opposite defaullts write commands

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/dotfiles#installation, first paragraph.

**Comment by lenn4rd** [comment]
Happened to me as well: the Dock showed the default app icon for every app launched. On one machine it was fixed after rebooting, on another rebooting didn't help. Looking through the `/Applications` folder the actual apps weren't affected, it seems to be a glitch in the Dock. I removed the affected apps from and added them to the Dock one by one and that solved this glitch for me.
