### ISSUE TITLE
Making Code signing with gpg persistent

### ISSUE THREAD

**Issue by lukasmue** [mathiasbynens/dotfiles#807]
Hi guys I added gpg code signing to my git configuration  with following commands:

```
git config --global gpg.program gpg1
git config --global user.signingkey  1234566789ABCDEF  
```

After updating the dotfiles with the bootstrap.sh script this configuration is gone. Does anyone know how to add these two options permanently to my environment?

**Comment by cemo** [comment]
https://github.com/mathiasbynens/dotfiles#add-custom-commands-without-creating-a-new-fork
