### ISSUE TITLE
`defaults write com.apple.screensaver askForPasswordDelay` doesn't work on High Sierra

### ISSUE THREAD

**Issue by chdiza** [mathiasbynens/dotfiles#809]
Has anyone else noticed that:
```
defaults write com.apple.screensaver askForPasswordDelay -int 0
```
doesn't work anymore on High Sierra?  It's supposed to change the setting that, in the GUI (System Preferences->Security->General), sets how long the machine has to be asleep or screen-savering before it will demand a password if woken.  But on High Sierra, even when I run that command, the delay remains at its default value of "5 minutes".

I sure hope there is an alternate, programmatic way to set this.

**Comment by blakek** [comment]
Has this been resolved in updates?  It's definitely working for me.  I use the control-shift-eject shortcut and it now immediately asks for the password where it didn't before.

**Comment by monfresh** [comment]
It's not working for me in Mojave.

**Comment by mcw0933** [comment]
Using `defaults write` no longer works as of 10.13.

https://blog.kolide.com/screensaver-security-on-macos-10-13-is-broken-a385726e2ae2
http://www.openradar.me/35462422

For those who have been searching for a way to do this via profiles, you can use this gist: 
https://gist.github.com/mcw0933/21b8a9e292e83c69931f5de0d2ae1883

**Comment by janosh** [comment]
Isn't it about time to remove

https://github.com/mathiasbynens/dotfiles/blob/66ba9b3cc0ca1b29f04b8e39f84e5b034fdb24b6/.macos#L223-L225

if they haven't been working for 5 years?
