### ISSUE TITLE
Could not write domain ~/Library/Preferences/ByHost/com.apple.systemuiserver

### ISSUE THREAD

**Issue by cassmtnr** [mathiasbynens/dotfiles#820]
Hello, I am kind new on OSX environment, learning about the dotfiles now, I am building my own following a guide. Got a mix between paulirish and mathiasbynens, getting what I want from them.

I use [Itsycal](https://www.mowglii.com/itsycal/) and want to hide the Clock from menu bar, it worked before just unchecking _Show date and time in menu bar_ at **System Preference > Date & Time > Clock**. 
Then after I first ran my .osx file that have the commands to hide Menu Bar icons, the Clock and Spotlight icons keep coming back, even if I go to **System Preferences** and uncheck the option, every time I reboot my Mac, both of them are there again.

Commands on my .osx file:

	
	sudo chmod 700 ~/Library/Preferences
	sudo chown "${UID}" ~/Library/Preferences
	
	# Menu bar: hide the Time Machine, Volume, and User icons
	for domain in ~/Library/Preferences/ByHost/com.apple.systemuiserver.*; do
		defaults write "${domain}" dontAutoLoad -array \
			"/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
			"/System/Library/CoreServices/Menu Extras/Volume.menu" \
			"/System/Library/CoreServices/Menu Extras/User.menu"
	done
	defaults write com.apple.systemuiserver menuExtras -array \
		"/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
		"/System/Library/CoreServices/Menu Extras/AirPort.menu" \
		"/System/Library/CoreServices/Menu Extras/Battery.menu" \
		"/System/Library/CoreServices/Menu Extras/Clock.menu"

	sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
	
  
When I run my .osx file I got the error on Terminal:

	bash .osx
	2018-01-03 01:07:50.515 defaults[2576:37988] Could not write domain /Users/cassiano/Library/Preferences/ByHost/com.apple.systemuiserver.013D9106-3475-5C6E-B6D1-88770AA105A6.013D9106-3475-5C6E-B6D1-88770AA105A6.013D9106-3475-5C6E-B6D1-88770AA105A6.013D9106-3475-5C6E-B6D1-88770AA105A6.013D9106-3475-5C6E-B6D1-88770AA105A6.plist; exiting
	2018-01-03 01:07:50.695 defaults[2580:38008] Could not write domain /Users/cassiano/Library/Preferences/ByHost/com.apple.systemuiserver.013D9106-3475-5C6E-B6D1-88770AA105A6.plist; exiting

My SIP status:

	csrutil status
	System Integrity Protection status: disabled.
	  

My dotfiles repository: https://github.com/cassianomon/dotfiles
  

Also my apps icons go missing after I run my .osx (https://prnt.sc/hvdsrh)

MacBook Pro (Retina, 15-inch, Mid 2015)
macOS High Sierra 10.13.2

**Comment by gibfahn** [comment]
Not sure if it's the same cause (got here by Googling my own issue) but I resolved my similar issue by adding my terminal app (e.g. Terminal.app, iTerm2, Alacritty, Kitty) to `System Preferences -> Privacy -> Full Disk Access`

**Comment by charlievaughan** [comment]
> Not sure if it's the same cause (got here by Googling my own issue) but I resolved my similar issue by adding my terminal app (e.g. Terminal.app, iTerm2, Alacritty, Kitty) to `System Preferences -> Privacy -> Full Disk Access`

@gibfahn this also worked when I needed to update /Library/Preferences/com.apple.TimeMachine
