### ISSUE TITLE
Show the ~/Library folder not working on macOS 10.13.2

### ISSUE THREAD

**Issue by Voleking** [mathiasbynens/dotfiles#824]
`sudo chflags nohidden ~/Library` doesn't work anymore.

**Comment by chdiza** [comment]
Yes it does.  I just did it after reading your issue :)

**Comment by Voleking** [comment]
@chdiza This issue happened after I reinstall macOS. After I tick the checkbox: Show Library Folder at Home folder View Option, `sudo chflags nohidden ~/Library` work again. Write here to help people who encounter the same problems.

<img width="233" alt="snipaste_2018-01-27_10-13-32" src="https://user-images.githubusercontent.com/13161779/35467600-a98107fe-034b-11e8-8ea3-33e0d2ea0ba4.png">

**Comment by niksy** [comment]
I just did complete macOS setup on new hardware and this option does not work. I had to go through same steps as @Voleking mentioned.
