### ISSUE TITLE
Don't use these files on Mojave!

### ISSUE THREAD

**Issue by itinance** [mathiasbynens/dotfiles#884]
It's obviously deprecated and should be declared as such.

I spend a whole day to install all tools on a new Macbook pro including node and Homebrew and all such things. Everything worked. Then (way to late I guess) I applied the dotfiles. Nothing is working anymore. Node doesn't find anything. "npm install xxx" will give "xxx not found". Same with Homebrew.  

Even a bash-shell can't be opened any more

**Comment by lucifer** [comment]
This just sounds like your Node environment needs a bit of attention. Starting from scratch is really not necessary.

**Comment by itinance** [comment]
$ echo $PATH
/usr/local/Cellar//usr/local/Cellar/:/Users/hagen/bin:/Users/hagen/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

$ git clone git@github.com:itinance/ncd-token.git
-bash: /usr/local/bin/git: No such file or directory


Nothing out of /usr/local/bin can be reached any more, although its in the PATH

**Comment by itinance** [comment]
Opening a new shell:

bash: /usr/local/bin/bash: No such file or directory
bash: line 0: exec: /usr/local/bin/bash: cannot execute: No such file or directory

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/dotfiles#installation

> **Warning:** If you want to give these dotfiles a try, you should first fork this repository, review the code, and remove things you don’t want or need. Don’t blindly use my settings unless you know what that entails. Use at your own risk!

**Comment by itinance** [comment]
I was my own fork that always worked well (unless I used it on a new Mojave installation).

Any ideas, why /usr/local/bin/bash can't be found in a new shell although it can be found in a current active shell?

**Comment by mathiasbynens** [comment]
I heard that the upcoming macOS version switches to zsh over bash by default. This might have something to do with that? Either way, I haven't played with Mojave yet so I cannot really help here.

**Comment by tagliala** [comment]
I'm using most of these files on Mojave 10.14.5 without any issue. I've used them both on an upgraded installation and a fresh one

FWIW, I'm not using `.macos` or `.osx` by my personal choice, so I don't know if the problem is there

**Comment by jeffbyrnes** [comment]
I can confirm @tagliala’s experience; I’ve been on Mojave since it was released, using my fork of these dot files, and they work fine. I also, however, don’t run the `.macos` script, though I used to.

I’m sure they’ll need some work once `zsh` becomes the default shell in macOS 10.15, though I’m planning on probably sticking with `bash` myself.

**Comment by jeffbyrnes** [comment]
@itinance as for not finding `/usr/local/bin/bash` in a new shell, that sounds like your `$PATH` isn’t being set early enough? Seems odd, that… you can take a look at how I scripted my initial Brew setup here: https://github.com/jeffbyrnes/dotfiles/blob/master/brew.sh#L21-L24

**Comment by lucifer** [comment]
To be fair @jeffbyrnes has done some great work on here of late. Thanks Jeff!

**Comment by lucifer** [comment]
> @itinance as for not finding `/usr/local/bin/bash` in a new shell, that sounds like your `$PATH` isn’t being set early enough? Seems odd, that… you can take a look at how I scripted my initial Brew setup here: https://github.com/jeffbyrnes/dotfiles/blob/master/brew.sh#L21-L24

https://scriptingosx.com/2019/02/install-bash-5-on-macos/

**Comment by itinance** [comment]
Many thanks to @jeffbyrnes! I switched to https://github.com/jeffbyrnes/dotfiles and it works brilliant. 

One of my issue was, that somehow the base shell was changed to /usr/local/bin/bash without any /usr/local/bin/bash existing. And somehow issues with $PATH after installation.

**Comment by jeffbyrnes** [comment]
That would definitely cause you some trouble. Glad my fork helped you out!

**Comment by itinance** [comment]
And as a second step, I solved the node-issues with this line:

`npm config set prefix /usr/local``

After installing the dotfiles, this config must have been wrong somehow, that no global installed node-based tool was working any more. With this setting everything was repaired around this.
