### ISSUE TITLE
Cannot remove Dropbox’s green checkmark icons in Finder

### ISSUE THREAD

**Issue by tshu-w** [mathiasbynens/dotfiles#898]
This [command](https://github.com/mathiasbynens/dotfiles/blob/master/.macos#L344
) cannot remove Dropbox’s green checkmark icons in finder now. Does anybody have other ideas?

macOS 10.15
Dropbox 83.4.152

**Comment by s10wen** [comment]
I'm on macOS 10.14 where it all looks good. Have you made sure the path is correct and the file is there? e.g.

```
# Change directory to the path, if this doesn't exist maybe you have Dropbox installed somewhere else
cd /Applications/Dropbox.app/Contents/Resources
# If the path does exist and so does the file, as a quick solution you could remove the file manually for now
ls -la | grep 'emb'
```

I'm looking to upgrade to 10.15 soon, but first I need to clean up my dotfiles, when I do I'll come back if still an issue :)

**Comment by TshuW** [comment]
@s10wen yes, the file seems renamed correctly, here is the result of `ls -la | grep 'emb'`
```
-rw-r--r--@   1 xxx  staff   1314421 Oct 16 02:12 DropboxTeamMemberFolderIconYosemite.icns
-rw-r--r--@   1 xxx  staff   1314731 Oct 16 02:12 DropboxTeamMemberFolderIconYosemite.icns.rsrc
-rw-r--r--@   1 xxx  staff    187948 Oct 16 02:12 emblem-dropbox-infinite.icns
-rw-r--r--@   1 xxx  staff    151671 Oct 16 02:12 emblem-dropbox-mixedstate.icns
-rw-r--r--@   1 xxx  staff    138454 Oct 16 02:12 emblem-dropbox-selsync.icns
-rw-r--r--@   1 xxx  staff    150111 Oct 16 02:12 emblem-dropbox-syncing.icns
-rw-r--r--@   1 xxx  staff    139172 Oct 16 02:12 emblem-dropbox-unsyncable.icns
-rw-r--r--@   1 xxx  staff    135425 Oct 16 02:12 emblem-dropbox-uptodate.icns.bak
```
however, the green checkmark icons are still there even after I restarting Finder, Dropbox and my Mac.

**Comment by s10wen** [comment]
Investigated some more and found some other files that looked similar:

```
overlay-uptodate.icns
up-to-date-v2.png
up-to-date-v2@2x.png
viewer-synced.png
viewer-synced@2x.png
```

I deleted all of those and tried to relaunch / kill finder but they were still showing. However!!! With a system reboot they now appear to be gone.

Please can you try as well? If this works for you as well, then it will be a case of finding out the correct one and updating the command to delete the correct one, or we could just update to delete them all :)

🤞🏻

**Comment by TshuW** [comment]
I remove all of the files you list, relaunch Finder, restart the system, reinstall dropbox fully and remove these files before opening it. But it doesn't work for me.

**Comment by s10wen** [comment]
Argh, just checked and mine have come back again!!! 🤷🏻‍♂️

**Comment by TshuW** [comment]
However, remove these files does impact some appearance, like the Up to date status at the left bottom when you click the Dropbox icon in the menu bar. So I don't know why it cannot work.
