### ISSUE TITLE
Looking how to Toggle 'Use Stacks' on Desktop

### ISSUE THREAD

**Issue by Drallas** [mathiasbynens/dotfiles#900]
I'm new to this and look how to Toggle 'Use Stacks' or how to discover where it might be stored as a defaults setting?

**Comment by kamui545** [comment]
```bash
defaults read > before.txt

# Toggle your setting...

defaults read > after.txt

# then show diff with your favourite tool
code --diff before.txt after.txt
```

**Comment by Drallas** [comment]
Thanks.. @kamui545 👍  

The settings is :

# Enable Use Stack on Desktop
defaults write com.apple.finder FXPreferredGroupBy -string "Kind"
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:GroupBy Kind" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy dateAdded" ~/Library/Preferences/com.apple.finder.plist
