### ISSUE TITLE
Vim background color makes it hard to read text

### ISSUE THREAD

**Issue by serv** [mathiasbynens/dotfiles#920]
![Screen Shot 2020-04-20 at 1 25 05 PM](https://user-images.githubusercontent.com/103456/79796435-6542a700-830a-11ea-996d-b7454d622179.png)

Does anyone else have this problem? 

The vim's background looks grey and it makes the text hard to read. Any idea how to make the background black?

**Comment by jamesacoughlin** [comment]
I think this may be caused by a conflict between the colorscheme set in your iterm profile, and the one in your vim config. Try changing your vim colorscheme to default via `:colorscheme default`, or messing around with your iTerm profile's `Colors` settings.

**Comment by serv** [comment]
I disabled solarized theme and started using `:colorscheme default` as you suggested.
