### ISSUE TITLE
git commit is not working after execute 

### ISSUE THREAD

**Issue by Shihara-Dilshan** [mathiasbynens/dotfiles#925]
when I try to commit it says
error: gpg failed to sign the data
fatal: failed to write commit object

**Comment by ealeksandrov** [comment]
Check https://github.com/mathiasbynens/dotfiles/issues/789

**Comment by Shihara-Dilshan** [comment]
https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0

I found a solution here
the asnwer from Andy Hayden
