### ISSUE TITLE
.bash_prompt "$" Bold issue

### ISSUE THREAD

**Issue by Damon-Hong** [mathiasbynens/dotfiles#930]
The default setup of "$" is bold. However, every time when I change the size of my terminal, the "$" will change the bold to regular mode. I don't know what is going on and how to fix this issue?

**Comment by Rudxain** [comment]
I have the same problem with GNOME-Terminal and Termux

**Comment by Rudxain** [comment]
https://github.com/termux/termux-app/discussions/4652
