### ISSUE TITLE
The link to Lauri Ranta's hidden preferences in the README now points to sketchy adult domains

### ISSUE THREAD

**Issue by bob-marcus** [mathiasbynens/dotfiles#943]
Hello, it seems that the `osxnotes` domain has been taken over by a scammer and now previous links to that site point to sketchy adult websites. Here is the Wayback Machine link that shows the original page
(https://web.archive.org/web/20161104144204/http://osxnotes.net/defaults.html).

**Comment by mathiasbynens** [comment]
Thank you!
